import type { Metadata } from "next";
import TickerLogo from "../components/TickerLogo";
import { loadNotes } from "../lib/notes";

export const metadata: Metadata = {
  title: "Research Notes",
  description: "Daily model-written research note, bull/bear debate and pre-mortem per stock.",
};

const ACTION_CLASS = { Buy: "Overweight", Hold: "Neutral", Sell: "Underweight" } as const;

export default function NotesPage() {
  const snapshot = loadNotes();
  const notes = [...(snapshot?.notes ?? [])].sort((a, b) => b.composite - a.composite);

  return (
    <main>
      <a className="back-link" href="/dashboard">← Risk dashboard</a>
      <h1>Research Notes</h1>
      {!snapshot ? (
        <div className="error">No notes yet -- they are generated by the daily dashboard run.</div>
      ) : (
        <>
          <p className="tagline">
            Written {snapshot.generatedAt} NZT by {snapshot.model.split("/").pop()} on Cloudflare Workers AI, from
            only the figures on the risk dashboard; any number it wrote that is not in those figures is flagged.
            Model opinion for research, not investment advice.
          </p>
          <ol className="ranking">
            {notes.map((n) => (
              <li key={n.ticker}>
                <a href={`#${n.ticker}`}>
                  <TickerLogo ticker={n.ticker} />
                  <span className="ticker">{n.ticker}</span>
                  <span className={`rank-score call ${ACTION_CLASS[n.action]}`}>{n.action}</span>
                </a>
              </li>
            ))}
          </ol>
          {notes.map((n) => (
            <section key={n.ticker} id={n.ticker} className="card note">
              <div className="card-head">
                <span className="ticker-id">
                  <TickerLogo ticker={n.ticker} />
                  <span className="ticker">{n.ticker}</span>
                </span>
                <span className={`composite call ${ACTION_CLASS[n.action]}`}>
                  {n.action} · {n.conviction} conviction
                </span>
              </div>
              <p className="thesis">{n.thesis}</p>
              {n.unverified.length > 0 && (
                <p className="stale">Contains numbers not in its source figures: {n.unverified.join(", ")}.</p>
              )}
              <div className="note-grid">
                <div>
                  <h3>Key data</h3>
                  <ul>{n.key_points.map((p, i) => <li key={i}>{p}</li>)}</ul>
                </div>
                <div>
                  <h3>Primary risks</h3>
                  <ul>{n.risks.map((p, i) => <li key={i}>{p}</li>)}</ul>
                </div>
              </div>
              <h3>Valuation</h3>
              <p>{n.valuation}</p>
              <div className="note-grid">
                <div>
                  <h3>Bull case</h3>
                  <ul>{n.bull.map((p, i) => <li key={i}>{p}</li>)}</ul>
                </div>
                <div>
                  <h3>Bear case</h3>
                  <ul>{n.bear.map((p, i) => <li key={i}>{p}</li>)}</ul>
                </div>
              </div>
              <p className="verdict">{n.debate_verdict}</p>
              <h3>Pre-mortem: down 40% in 12 months — what went wrong?</h3>
              <div className="table-wrap">
                <table className="sector-table">
                  <thead>
                    <tr>
                      <th>Reason</th>
                      <th className="num">Probability</th>
                      <th>Early warning sign</th>
                    </tr>
                  </thead>
                  <tbody>
                    {[...n.premortem].sort((a, b) => b.probability - a.probability).map((p, i) => (
                      <tr key={i}>
                        <td>{p.reason}</td>
                        <td className="num">{p.probability}%</td>
                        <td>{p.warning_sign}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </section>
          ))}
        </>
      )}
    </main>
  );
}
